### ISSUE TITLE
ERROR: manifest for anycable/anycable-go:1.0

### ISSUE THREAD

**Issue by Yegorov** [anycable/anycable_rails_demo#3]
Hello, @palkan 
I had some error when run project

```
$ dip up rails anycable
Pulling ws (anycable/anycable-go:1.0)...
ERROR: manifest for anycable/anycable-go:1.0 not found: manifest unknown: manifest unknown
```

And fixed it by replacing [this line](https://github.com/anycable/anycable_rails_demo/blob/master/docker-compose.yml#L86) to `image: anycable/anycable-go:1.0.0-alpine`

**Comment by palkan** [comment]
Thanks for reporting this. Looks like we haven't pushed some image tags.

**Comment by palkan** [comment]
Fixed. Now all `1`, `1.0` images are available.
